### ISSUE TITLE
JavaScript error on page log of TextBox

### ISSUE THREAD

**Issue by timja** [jenkinsci/design-library-plugin#29]
### Jenkins and plugins versions report

https://weekly.ci.jenkins.io/design-library/TextBox/

2.342

### What Operating System are you using (both controller, and any agents involved in the problem)?

Chrome 100.0

### Reproduction steps

Open https://weekly.ci.jenkins.io/design-library/TextBox/ and check the browser console

### Expected Results

No error

### Actual Results

```
hudson-behavior.js:49 TypeError: e.getAttribute is not a function
    at findFormParent (hudson-behavior.js:2067:22)
    at findNearBy (hudson-behavior.js:275:17)
    at hudson-behavior.js:1532:21
    at hudson-behavior.js:47:13
    at prototype.js:853:18
    at Array.forEach (<anonymous>)
    at Array.each (prototype.js:852:12)
    at refillOnChange (hudson-behavior.js:1531:22)
    at combobox.js:15:9
    at Array.forEach (<anonymous>)
```

**Comment by timja** [comment]
Might be fixed although I'm now getting:

```
Failed to parse codemirror-config '{lineNumbers: true}' as JSON SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)
    at JSON.parse (<anonymous>)
    at textarea.js:7:19
    at Array.forEach (<anonymous>)
    at behavior.js:135:22
    at Array.forEach (<anonymous>)
    at behavior.js:126:21
    at Array.forEach (<anonymous>)
    at Object.applySubtree (behavior.js:107:15)
    at Object.apply (behavior.js:90:12)
    at behavior.js:85:19
```

https://weekly.ci.jenkins.io/design-library/Inputs/
